In [1]:
from sqlalchemy import create_engine
import pandas as pd

df = pd.read_csv('cleaned_retail_data.csv')

engine = create_engine('postgresql://postgres:2009@localhost:5432/retail_analytics')

In [3]:
from sqlalchemy import text

with engine.connect() as conn:
    conn.execute(text("DROP TABLE IF EXISTS transactions;"))
    conn.commit()

In [4]:
df.to_sql(
    'transactions',
    engine,
    if_exists='replace',
    index=False,
    method='multi',
    chunksize=5000
)
print("Done — table loaded.")

Done — table loaded.

In [6]:
result = pd.read_sql("SELECT * FROM transactions LIMIT 5;", engine)
result

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,TotalPrice
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-12-01 07:45:00,6.95,13085.0,United Kingdom,83.4
1,489434,79323P,PINK CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom,81.0
2,489434,79323W,WHITE CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom,81.0
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009-12-01 07:45:00,2.10,13085.0,United Kingdom,100.8
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-12-01 07:45:00,1.25,13085.0,United Kingdom,30.0

In [8]:
query1 = """
SELECT
  DATE_TRUNC('month', "InvoiceDate"::timestamp) AS month,
  ROUND(SUM("TotalPrice")::numeric, 2) AS revenue
FROM transactions
GROUP BY month
ORDER BY month;
"""

result1 = pd.read_sql(query1, engine)
result1

        month     revenue
0  2009-12-01   683504.01
1  2010-01-01   555802.67
2  2010-02-01   504558.96
3  2010-03-01   696978.47
4  2010-04-01   591982.00
5  2010-05-01   597833.38
6  2010-06-01   636371.13
7  2010-07-01   589736.17
8  2010-08-01   602224.60
9  2010-09-01   829013.95
10 2010-10-01  1033112.01
11 2010-11-01  1166460.02
12 2010-12-01   570422.73
13 2011-01-01   568101.31
14 2011-02-01   446084.92
15 2011-03-01   594081.76
16 2011-04-01   468374.33
17 2011-05-01   677355.15
18 2011-06-01   660046.05
19 2011-07-01   598962.90
20 2011-08-01   644051.04
21 2011-09-01   950690.20
22 2011-10-01  1035642.45
23 2011-11-01  1156205.61
24 2011-12-01   517208.44

In [9]:
query2 = """
SELECT
  "Description",
  SUM("Quantity") AS units_sold,
  ROUND(SUM("TotalPrice")::numeric, 2) AS revenue
FROM transactions
GROUP BY "Description"
ORDER BY revenue DESC
LIMIT 10;
"""

result2 = pd.read_sql(query2, engine)
result2

                          Description  units_sold    revenue
0            REGENCY CAKESTAND 3 TIER     24124.0  277656.25
1  WHITE HANGING HEART T-LIGHT HOLDER     91757.0  247048.01
2         PAPER CRAFT , LITTLE BIRDIE     80995.0  168469.60
3                              Manual      9384.0  151777.67
4             JUMBO BAG RED RETROSPOT     74224.0  134307.44
5                             POSTAGE      5235.0  124648.04
6       ASSORTED COLOUR BIRD ORNAMENT     78234.0  124351.86
7                       PARTY BUNTING     23460.0  103283.38
8      MEDIUM CERAMIC TOP STORAGE JAR     77916.0   81416.73
9     PAPER CHAIN KIT 50'S CHRISTMAS      28380.0   76598.18

In [10]:
query3 = """
SELECT
  "Country",
  ROUND(SUM("TotalPrice")::numeric, 2) AS revenue,
  COUNT(DISTINCT "CustomerID") AS customers
FROM transactions
GROUP BY "Country"
ORDER BY revenue DESC;
"""

result3 = pd.read_sql(query3, engine)
result3

                 Country      revenue  customers
0         United Kingdom  14389234.92       5350
1                   EIRE    616570.54          5
2            Netherlands    554038.09         22
3                Germany    425019.71        107
4                 France    348768.96         95
5              Australia    169283.46         15
6                  Spain    108332.49         41
7            Switzerland    100061.94         22
8                 Sweden     91515.82         19
9                Denmark     68580.69         12
10               Belgium     65387.82         29
11                Norway     56322.50         13
12              Portugal     55554.78         24
13       Channel Islands     44623.33         13
14                 Japan     43023.91         10
15                 Italy     32108.17         17
16               Finland     29925.54         14
17             Singapore     25317.06          1
18                Cyprus     24849.95         11
19               Austria     23613.01         13
20                Greece     19096.19          5
21                Poland     10654.29          6
22                Israel     10415.24          4
23  United Arab Emirates      9202.69          4
24           Unspecified      8607.35          6
25                   USA      8366.86          9
26                 Malta      8099.09          2
27               Iceland      4921.53          1
28             Lithuania      4892.68          1
29                Canada      4883.04          5
30              Thailand      3070.54          1
31                   RSA      1933.74          2
32               Lebanon      1693.88          1
33                Brazil      1411.87          2
34               Bahrain      1354.37          2
35    European Community      1300.25          1
36                 Korea      1118.51          2
37        Czech Republic       826.74          1
38           West Indies       536.41          1
39          Saudi Arabia       145.92          1
40               Nigeria       140.39          1

In [11]:
query4 = """
SELECT
  CASE WHEN order_count = 1 THEN 'One-time' ELSE 'Repeat' END AS customer_type,
  COUNT(*) AS num_customers
FROM (
  SELECT "CustomerID", COUNT(DISTINCT "InvoiceNo") AS order_count
  FROM transactions
  GROUP BY "CustomerID"
) sub
GROUP BY customer_type;
"""

result4 = pd.read_sql(query4, engine)
result4

  customer_type  num_customers
0      One-time           1623
1        Repeat           4255

In [12]:
query5 = """
SELECT
  DATE_TRUNC('month', "InvoiceDate"::timestamp) AS month,
  ROUND(AVG("order_total")::numeric, 2) AS avg_order_value
FROM (
  SELECT "InvoiceNo", "InvoiceDate", SUM("TotalPrice") AS order_total
  FROM transactions
  GROUP BY "InvoiceNo", "InvoiceDate"
) order_totals
GROUP BY month
ORDER BY month;
"""

result5 = pd.read_sql(query5, engine)
result5

        month  avg_order_value
0  2009-12-01           451.75
1  2010-01-01           549.76
2  2010-02-01           457.03
3  2010-03-01           456.14
4  2010-04-01           444.76
5  2010-05-01           433.84
6  2010-06-01           424.53
7  2010-07-01           426.73
8  2010-08-01           463.25
9  2010-09-01           488.23
10 2010-10-01           484.12
11 2010-11-01           449.85
12 2010-12-01           407.15
13 2011-01-01           572.11
14 2011-02-01           445.19
15 2011-03-01           448.70
16 2011-04-01           406.22
17 2011-05-01           434.48
18 2011-06-01           473.49
19 2011-07-01           450.01
20 2011-08-01           502.38
21 2011-09-01           541.40
22 2011-10-01           536.60
23 2011-11-01           434.83
24 2011-12-01           664.79

In [13]:
result1.to_csv('monthly_revenue.csv', index=False)
result2.to_csv('top_products.csv', index=False)
result3.to_csv('revenue_by_country.csv', index=False)
result4.to_csv('repeat_vs_onetime.csv', index=False)
result5.to_csv('avg_order_value.csv', index=False)